Update README file
webosose/ares-cli pull request #100
Opened 2024-02-28 09:35 UTC by kclod-kim

:Release Notes:
Update README file

:Detailed Notes:
Update information of @webosose/ares-cli

:Testing Performed:
1. Checked CLI unit test
2. Checked API unit test
3. Checked README file

:Issues Addressed:
[WRQ-9026] Update README.md

2024-02-28 09:36 UTC, kclod-kim commented
code :+1: 
verify :+1:

2024-02-29 04:57 UTC, ssuminahn commented
@Heeam-Shin 선임님, 
해당 건 내용 리뷰 부탁드립니다.

2024-02-29 05:01 UTC, Heeam-Shin commented
@ssuminahn 선임님,

이게 혹시 GitHub으로만 공개할 repository인가요?

2024-02-29 05:02 UTC, Heeam-Shin commented on README.md
> +There is no further maintenance here.
```suggestion
This repository has been deprecated since March 4, 2024.
```

2024-02-29 05:03 UTC, Heeam-Shin commented on README.md
> +There is no further maintenance here.
- 언제부터 지원이 종료되었는지 명시하는 것이 좋습니다.
- 줄바꿈을 하고 싶으시면 한 줄 더 띄어쓰기 하셔야 됩니다.

2024-02-29 05:04 UTC, ssuminahn commented
> @ssuminahn 선임님,
> 
> 이게 혹시 GitHub으로만 공개할 repository인가요? 그런 경우라면 제일 상단으로 내용을 올리고 아래와 같은 노트 스타일을 적용하는 편이 나아보입니다.
> 
> https://docs.github.com/ko/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

important 정도이면 될까요? 어떤 레벨 생각하시나요?
현재로서 해당 문구 추가 반영은 github만 생각하고 있습니다.

2024-02-29 05:07 UTC, Heeam-Shin commented
important보다는 warning 혹은 caution이 좀 더 의미가 맞을 것 같습니다. caution은 좀 센거 같아서 warning 추천합니다.

2024-02-29 05:09 UTC, Heeam-Shin commented
노트 스타일 적용한다면 해당 내용들은(announce 내용 전부, 헤딩은 없이) summary 보다도 위로 배치하는 것이 적절해보입니다.

2024-02-29 05:45 UTC, ssuminahn commented
@kclod-kim 책임님, 
위 신선임님 코멘트 반영해서 한번 샘플 보면 좋을 것 같아요

2024-02-29 06:12 UTC, kclod-kim commented
@ssuminahn 선임님, @Heeam-Shin 선임님.

waring 으롭 변경하였습니다.
줄바꿈은 전체적인 문서 스타일에 따라 적용하지 않았습니다.

2024-02-29 06:54 UTC, kclod-kim commented
@ssuminahn 선임님, @Heeam-Shin 선임님.
"we plan to develop and maintain a single webOS CLI to support multi webOS in @webos-sdk/cli."
로 추가 수정하였으니 확인 부탁드립니다.

2024-02-29 07:16 UTC, ssuminahn approved these changes
code :+1: 
verify :+1:

2024-02-29 07:59 UTC, ssuminahn requested changes

2024-02-29 07:59 UTC, ssuminahn commented on README.md
> +This repository has been deprecated since March 4, 2024.
@kclod-kim 책임님, 
해당 라인 새로운 라인으로 내리고 싶으시면 앞에 new line 하나 더 넣으시고, 
한 문단에 같이 쓰실거면 앞으로 붙여주세요~

2024-02-29 08:22 UTC, kclod-kim commented
@ssuminahn 선임님
new line없이 위로 올리는 것으로 수정했습니다.

2024-02-29 08:25 UTC, ssuminahn approved these changes
code :+1:

2024-03-04 10:40 UTC, merged