:Release Notes:
webosose/ares-cli pull request #35
Opened 2021-05-24 06:08 UTC by ssuminahn

Support to save file in follow option on ares-log

:Detailed Notes:
- Modify to support both save and follow options at same time

:Testing Performed:
1. Pass unit test on ose and auto emulator
2. Pass eslint
3. Check below command and output format
- ares-log -f -s saved.log

:Issues Addressed:
[PLAT-143147] Support to save file in follow option on ares-log

2021-05-24 06:09 UTC, ssuminahn reviewed
code :+1: 
verify :+1:

2021-05-25 07:52 UTC, YoungeunKim requested changes
Code :-1: 
Verified :+1: 

Just fix minor things.

2021-05-25 07:52 UTC, YoungeunKim commented on lib/log.js
> +                    next(err, {msg : "\nCreated " + options.argv.argv.remain[0] +"\nSuccess"});
minor things : 
+(space)"\nSuccess"

2021-05-25 07:52 UTC, YoungeunKim commented on lib/log.js
> +                    next(err, {msg : "\nCreated " + options.argv.argv.remain[0] +"\nSuccess"});
minor things : 
+(space)"\nSuccess"

2021-05-25 09:11 UTC, ssuminahn reviewed
code :+1: 
verify :+1:

2021-05-25 09:12 UTC, ssuminahn commented on lib/log.js
> +                    next(err, {msg : "\nCreated " + options.argv.argv.remain[0] +"\nSuccess"});
I've update this.

2021-05-25 09:12 UTC, ssuminahn commented on lib/log.js
> +                    next(err, {msg : "\nCreated " + options.argv.argv.remain[0] +"\nSuccess"});
I've update this.

2021-05-25 22:42 UTC, YoungeunKim commented on lib/log.js
> -                    next(null, {msg : "\nCreated " + options.argv.argv.remain[0] +"\nSuccess"});
Why did you remove this line?

2021-05-25 23:06 UTC, YoungeunKim approved these changes
Code 👍 
Verified 👍

2021-05-26 00:44 UTC, merged