Add time interval setting in unit test
webosose/ares-cli pull request #51
Opened 2021-07-30 03:34 UTC by ssuminahn

:Release Notes:
Add time interval setting in unit test

:Detailed Notes:
- Sometimes unit test failure due to time out occurs.
  when executing unit test depending on host pc performance.
- Added time interval setting when run the unit test to solve the problem.

:Testing Performed:
1. Pass unit test on ose
2. Pass eslint
3. Check time interval setting and test result
3-1. Change default time interval to fail the unit test
3-2. Check to no unit test failure when executing unit test command as like,
    $ jsamine --device=ose --ip=123.456.789.10 --timeInterval=12000

:Issues Addressed:
[WRN-2921] Add function to modify default timeout interval

2021-07-30 03:38 UTC, ssuminahn commented
@YoungeunKim 
For your verification, you change jasmine.DEFAULT_TIMEOUT_INTERVAL to smaller in spec/helpers/reporter.js.
And then, you execute unit test command adding timeInterval to larger.

2021-07-30 03:38 UTC, ssuminahn reviewed
code :+1: 
verify :+1:

2021-08-02 05:53 UTC, YoungeunKim requested changes
Please modify minor things. 
Code :-1: 
Verified :+1: (excect 'ares-device -c -dp 1' case. Need to connect the cable)

2021-08-03 00:59 UTC, ssuminahn reviewed
code :+1: 
verify :+1: 

@YoungeunKim 
I change TimeInterval to timeInterval of printed information.
Please review this.

2021-08-03 01:00 UTC, ssuminahn commented on spec/jsSpecs/common-spec.js
> +        if (argv.timeInterval){
I fixed this.

2021-08-03 01:29 UTC, YoungeunKim commented on spec/jsSpecs/common-spec.js
> +        console.info(`device : ${options.device}, ip : ${options.ip}, port : ${options.port}, timeInterval : ${jasmine.DEFAULT_TIMEOUT_INTERVAL}`);
timeInterval is better than "TimeInverval"

2021-08-03 02:44 UTC, YoungeunKim commented
Code :+1: 
Verified :+1:

2021-08-03 04:43 UTC, YoungeunKim approved these changes

2021-08-03 04:46 UTC, ssuminahn commented
> Code 
> Verified 
> 
> One thing to be modified in commit message :
> "jsamine" ->"jasmine"
> ` $ jsamine --device=ose --ip=123.456.789.10 --timeInterval=12000`

Thank you for catching my mistake. I've updated it.

2021-08-03 04:46 UTC, merged